- pipes/01-mp-pipe.py
- pipes/04-vote-pipe.py
> Optimize performance for vote pipe

- pipes/committee_pipe.py
- pipes/mp_committee_membership_pipe.py
- postgres-init-scripts/01_create_tables.sql
Add committee and committee membership tables and pipes. Committee table created for further development.  In both, pipe search is limited to MP retirement at 2000-01-01, i.e. includes only the committees including MP(s) who are active or retired after 2000-01-01.
> feat: :sparkles: Add committees+memberships tables and pipes

- pipes/SELECT id,.sql
- pipes/ballot_pipe.py
- postgres-init-scripts/01_create_tables.sql
tulee tarpeeseen myöhemmin, trust
> feat: :sparkles: Add parliament_id to ballot table

- pipes/mp_pipe.py
oli kiusallinen dicti str avaimil ja koitettii int idtä
> fix: mp photos comparing string to int

- Makefile
nii et voi ajaa `make install frontend` kylmiltee ja homma pelaa
> feat: add frontend install make script

- frontend/src/pages/edustaja/[memberOfParliament]/aanestykset.astro
- frontend/src/pages/edustaja/[memberOfParliament]/index.astro
- frontend/src/pages/edustaja/[memberOfParliament]/votes/index.astro
Create a votes page for MPs, and styles the votes list a little.
> feat: :sparkles: add votes page for mp

- .vscode/workspace.code-workspace
- frontend/src/database.ts
- frontend/src/pages/edustaja/[memberOfParliament]/aanestykset.astro
- frontend/src/pages/edustaja/[memberOfParliament]/index.astro
- frontend/src/pages/index.astro
- frontend/tsconfig.json
nää on vähä kivompii lukee ja käyttää heti ku tulee pari filun siirtotyylist refaktorii
> refactor: prefer absolute imports in components

- .vscode/workspace.code-workspace
- frontend/src/components/MemberListItem.astro
- frontend/src/components/ProfilePhoto.astro
- frontend/src/database.ts
- frontend/src/pages/edustaja/[memberOfParliament]/aanestykset.astro
- frontend/src/pages/edustaja/[memberOfParliament]/index.astro
- frontend/src/pages/index.astro
- frontend/tsconfig.json
this will be needed in the generic mp layout in addition to the mp listing
> feat: add separate component for mp profile photos

- frontend/src/pages/edustaja/[memberOfParliament]/_layout.astro
- frontend/src/pages/edustaja/[memberOfParliament]/jäsenyydet.astro
Adds committee memberships to the MP page under the "jäsenyydet" tab (renamed from "Virat").
> feat: :sparkles: add committee memberships page

- pipes/mp_pipe.py
> fix: :bug: fix mp_pipe order to preprocess first and then import

- frontend/src/layouts/Layout.astro
> feat: :sparkles: add simple navigation bar

- pipes/mp_party_membership_pipe.py
> Fix mp_party_membership_pipe

- pipes/speech_pipe.py
- postgres-init-scripts/01_create_tables.sql
https://github.com/boyswithoutsockson/eduri/issues/66
> Add response field to speech

- frontend/src/pages/edustaja/[memberOfParliament]/_layout.astro
- frontend/src/pages/edustaja/[memberOfParliament]/_utils.ts
- frontend/src/pages/edustaja/[memberOfParliament]/aanestykset.astro
- frontend/src/pages/edustaja/[memberOfParliament]/index.astro
- frontend/src/pages/edustaja/[memberOfParliament]/jasenyydet.astro
- frontend/src/pages/edustaja/[memberOfParliament]/puheenvuorot.astro
previously the urls were `/edustaja/Pauli Juhani Aalto-Setälä`, now it would be `/edustaja/Pauli+Aalto-Setälä`
> refactor: use mp urls from first+last instead of full name

- Makefile
> feat: add cleaning scripts to makefile

- Makefile
- pipes/agenda_item_pipe.py
- pipes/harmonize.py
- pipes/mp_parliamentary_group_membership_pipe.py
- pipes/parties_pipe.py
- postgres-init-scripts/01_create_tables.sql
> rename parties to parliament groups

- pipes/minister_pipe.py
> Fix bug in minister pipe

- Makefile
> fix: add election seasons preprocess dep

- frontend/src/components/MPSearch.tsx
- frontend/src/database.gen.d.ts
- frontend/src/pages/data.json.ts
- frontend/src/pages/index.astro
tää salee toimis sit ku ministry pipe ei palauta samaa start ja end datee kaikille #95
> feat: show mp ministry in listing

- Makefile
nyt kaikki mitä voidaan ajetaan niin rinnan ku voidaan, merkittävänä muutoksena `make nuke database` ei enää toimi, vaan pitää ajaa joko `make nuke` ja `make database` erikseen, tai `make nuke-database` joka toimii kuten aiempiki
> feat: parallelize makefile execution

- Makefile
> fix: add mp insertion as dependency for government proposals

- pipes/XML_parsing_help_functions.py
- pipes/committee_reports_pipe.py
- pipes/government_proposals_pipe.py
- pipes/mp_law_proposals_pipe.py
- pipes/mp_petition_proposals_pipe.py
- postgres-init-scripts/01_create_tables.sql
> feat: :sparkles: Add dates to proposals and committee reports

- frontend/src/pages/edustajat/[memberOfParliament]/_utils.ts
aiemmin tost tuli duplikaattirivejä per ekryhmä mihin ke oli kuulunu
> fix: mp pg joining

- frontend/src/pages/edustajat/[memberOfParliament]/_utils.ts
- frontend/src/pages/edustajat/data.json.ts
- frontend/src/pages/edustajat/index.astro
same functionality, less duplicated code
> refactor: simplify mp data querying

- frontend/src/components/ProfilePhoto.astro
- frontend/src/pages/edustajat/[memberOfParliament]/_layout.astro
noi actions-putket oli solmus ku olin burgeroinu jotai
> fix: use mp first + last instead of full name
